package com.videodb.entity;

// Generated Mar 14, 2020, 3:47:13 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;



/**
 * Videos generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name = "Videos.findAll", query = "Select v from Videos v "),
	@NamedQuery(name = "Videos.findByURL", query = "SELECT v FROM Videos v WHERE v.url = :url"),
	@NamedQuery(name = "Videos.findByComedian", query = "SELECT v FROM Videos v JOIN Comedians c"
			+ " ON v.comedians.comedianId = c.comedianId AND c.comedianId = :comId"),
	@NamedQuery(name = "Videos.listbyUser", query = "SELECT v FROM Videos v JOIN Users u"
			+ " ON v.users.userId = u.userId AND u.userId = :userId"),
	
	@NamedQuery(name = "Videos.search", query = "SELECT v FROM Videos v JOIN Comedians c"
			+ " ON v.comedians.comedianId = c.comedianId WHERE v.tags LIKE '%' || :keyword || '%'"
			+ " OR c.lastName LIKE '%' || :keyword || '%'"
			+ " OR c.firstName LIKE '%' || :keyword || '%'"),


	})

@NamedNativeQueries({
	@NamedNativeQuery(name = "Videos.PoorYouTube", query = "select * from videos left join reviews " + 
			"on videos.video_id = reviews.videoId where score= 'Poor' group by video_id" , resultClass = Videos.class),
	@NamedNativeQuery(name = "Videos.findByUser", query = "select * from videos where userId = ?" , resultClass = Videos.class),
})
@Table(name = "videos", catalog = "videodb", uniqueConstraints = @UniqueConstraint(columnNames = "URL"))
public class Videos implements java.io.Serializable {

	private Integer videoId;
	private Comedians comedians;
	private Users users;
	private String url;
	private String tittle;
	private String description;
	private Date date;
	private String tags;
	private Set<Reviews> reviewses = new HashSet<Reviews>(0);

	public Videos() {
	}
	
	public Videos(Comedians comedians, String url, String tittle, String description, Date date, String tags) {
		this.comedians = comedians;
		this.url = url;
		this.tittle = tittle;
		this.description = description;
		this.date = date;
		this.tags = tags;
	}
	public Videos(Comedians comedians,Users users, String url, String tittle, String description, Date date, String tags) {
		this.comedians = comedians;
		this.users = users;
		this.url = url;
		this.tittle = tittle;
		this.description = description;
		this.date = date;
		this.tags = tags;
	}

	public Videos(Comedians comedians, String url, String tittle, String description, Date date, String tags,
			Set<Reviews> reviewses) {
		this.comedians = comedians;
		this.url = url;
		this.tittle = tittle;
		this.description = description;
		this.date = date;
		this.tags = tags;
		this.reviewses = reviewses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "video_id", unique = true, nullable = false)
	public Integer getVideoId() {
		return this.videoId;
	}

	public void setVideoId(Integer videoId) {
		this.videoId = videoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comedianId")
	public Comedians getComedians() {
		return this.comedians;
	}

	public void setComedians(Comedians comedians) {
		this.comedians = comedians;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	
	@Column(name = "URL", unique = true, length = 45)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "tittle", length = 45)
	public String getTittle() {
		return this.tittle;
	}

	public void setTittle(String tittle) {
		this.tittle = tittle;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Tags", length = 45)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "videos")
	public Set<Reviews> getReviewses() {
		return this.reviewses;
	}

	public void setReviewses(Set<Reviews> reviewses) {
		this.reviewses = reviewses;
	}


}
