package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Comedian generated by hbm2java
 */
@Entity
@Table(name = "comedian", catalog = "inheritancedb")
public class Comedian implements java.io.Serializable {

	private ComedianId id;

	public Comedian() {
	}

	public Comedian(ComedianId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "firstName", column = @Column(name = "firstName", length = 30)),
			@AttributeOverride(name = "lastName", column = @Column(name = "lastName", length = 30)),
			@AttributeOverride(name = "birthDay", column = @Column(name = "birthDay")),
			@AttributeOverride(name = "birthPlace", column = @Column(name = "birthPlace", length = 10)),
			@AttributeOverride(name = "personId", column = @Column(name = "person_id")),
			@AttributeOverride(name = "street", column = @Column(name = "street", length = 30)),
			@AttributeOverride(name = "city", column = @Column(name = "city", length = 30)),
			@AttributeOverride(name = "state", column = @Column(name = "state", length = 30)) })
	public ComedianId getId() {
		return this.id;
	}

	public void setId(ComedianId id) {
		this.id = id;
	}

}
