package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comedians generated by hbm2java
 */
@Entity
@Table(name = "comedians", catalog = "videodb")
public class Comedians implements java.io.Serializable {

	private Integer comedianId;
	private String firstName;
	private String lastName;
	private Date birthDay;
	private String birthPlace;
	private Set<Favcomedians> favcomedianses = new HashSet<Favcomedians>(0);
	private Set<Videos> videoses = new HashSet<Videos>(0);

	public Comedians() {
	}

	public Comedians(String firstName, String lastName, Date birthDay, String birthPlace) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDay = birthDay;
		this.birthPlace = birthPlace;
	}

	public Comedians(String firstName, String lastName, Date birthDay, String birthPlace,
			Set<Favcomedians> favcomedianses, Set<Videos> videoses) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDay = birthDay;
		this.birthPlace = birthPlace;
		this.favcomedianses = favcomedianses;
		this.videoses = videoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "comedian_id", unique = true, nullable = false)
	public Integer getComedianId() {
		return this.comedianId;
	}

	public void setComedianId(Integer comedianId) {
		this.comedianId = comedianId;
	}

	@Column(name = "firstName", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthDay", nullable = false, length = 10)
	public Date getBirthDay() {
		return this.birthDay;
	}

	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	@Column(name = "birthPlace", nullable = false, length = 45)
	public String getBirthPlace() {
		return this.birthPlace;
	}

	public void setBirthPlace(String birthPlace) {
		this.birthPlace = birthPlace;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comedians")
	public Set<Favcomedians> getFavcomedianses() {
		return this.favcomedianses;
	}

	public void setFavcomedianses(Set<Favcomedians> favcomedianses) {
		this.favcomedianses = favcomedianses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comedians")
	public Set<Videos> getVideoses() {
		return this.videoses;
	}

	public void setVideoses(Set<Videos> videoses) {
		this.videoses = videoses;
	}

}
