package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comedian1 generated by hbm2java
 */
@Entity
@Table(name = "comedian1", catalog = "dbtrain")
public class Comedian1 implements java.io.Serializable {

	private Integer comedianid;
	private Integer birthday;
	private String birthplace;
	private Integer personId;
	private String street;
	private String city;
	private String state;

	public Comedian1() {
	}

	public Comedian1(Integer birthday, String birthplace, Integer personId, String street, String city, String state) {
		this.birthday = birthday;
		this.birthplace = birthplace;
		this.personId = personId;
		this.street = street;
		this.city = city;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "comedianid", unique = true, nullable = false)
	public Integer getComedianid() {
		return this.comedianid;
	}

	public void setComedianid(Integer comedianid) {
		this.comedianid = comedianid;
	}

	@Column(name = "BIRTHDAY")
	public Integer getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Integer birthday) {
		this.birthday = birthday;
	}

	@Column(name = "BIRTHPLACE", length = 45)
	public String getBirthplace() {
		return this.birthplace;
	}

	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	@Column(name = "person_id")
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "street", length = 30)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
