package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComedianId generated by hbm2java
 */
@Embeddable
public class ComedianId implements java.io.Serializable {

	private String firstName;
	private String lastName;
	private Integer birthDay;
	private String birthPlace;
	private Integer personId;
	private String street;
	private String city;
	private String state;

	public ComedianId() {
	}

	public ComedianId(String firstName, String lastName, Integer birthDay, String birthPlace, Integer personId,
			String street, String city, String state) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDay = birthDay;
		this.birthPlace = birthPlace;
		this.personId = personId;
		this.street = street;
		this.city = city;
		this.state = state;
	}

	@Column(name = "firstName", length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "birthDay")
	public Integer getBirthDay() {
		return this.birthDay;
	}

	public void setBirthDay(Integer birthDay) {
		this.birthDay = birthDay;
	}

	@Column(name = "birthPlace", length = 10)
	public String getBirthPlace() {
		return this.birthPlace;
	}

	public void setBirthPlace(String birthPlace) {
		this.birthPlace = birthPlace;
	}

	@Column(name = "person_id")
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "street", length = 30)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComedianId))
			return false;
		ComedianId castOther = (ComedianId) other;

		return ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
				&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null
						&& castOther.getLastName() != null && this.getLastName().equals(castOther.getLastName())))
				&& ((this.getBirthDay() == castOther.getBirthDay()) || (this.getBirthDay() != null
						&& castOther.getBirthDay() != null && this.getBirthDay().equals(castOther.getBirthDay())))
				&& ((this.getBirthPlace() == castOther.getBirthPlace()) || (this.getBirthPlace() != null
						&& castOther.getBirthPlace() != null && this.getBirthPlace().equals(castOther.getBirthPlace())))
				&& ((this.getPersonId() == castOther.getPersonId()) || (this.getPersonId() != null
						&& castOther.getPersonId() != null && this.getPersonId().equals(castOther.getPersonId())))
				&& ((this.getStreet() == castOther.getStreet()) || (this.getStreet() != null
						&& castOther.getStreet() != null && this.getStreet().equals(castOther.getStreet())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getBirthDay() == null ? 0 : this.getBirthDay().hashCode());
		result = 37 * result + (getBirthPlace() == null ? 0 : this.getBirthPlace().hashCode());
		result = 37 * result + (getPersonId() == null ? 0 : this.getPersonId().hashCode());
		result = 37 * result + (getStreet() == null ? 0 : this.getStreet().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		return result;
	}

}
