package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PersonNicknames generated by hbm2java
 */
@Entity
@Table(name = "person_nicknames", catalog = "dbtrain")
public class PersonNicknames implements java.io.Serializable {

	private PersonNicknamesId id;

	public PersonNicknames() {
	}

	public PersonNicknames(PersonNicknamesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "personPersonId", column = @Column(name = "person_person_id")),
			@AttributeOverride(name = "nickname", column = @Column(name = "nickname", length = 30)) })
	public PersonNicknamesId getId() {
		return this.id;
	}

	public void setId(PersonNicknamesId id) {
		this.id = id;
	}

}
