package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonNicknamesId generated by hbm2java
 */
@Embeddable
public class PersonNicknamesId implements java.io.Serializable {

	private Integer personPersonId;
	private String nickname;

	public PersonNicknamesId() {
	}

	public PersonNicknamesId(Integer personPersonId, String nickname) {
		this.personPersonId = personPersonId;
		this.nickname = nickname;
	}

	@Column(name = "person_person_id")
	public Integer getPersonPersonId() {
		return this.personPersonId;
	}

	public void setPersonPersonId(Integer personPersonId) {
		this.personPersonId = personPersonId;
	}

	@Column(name = "nickname", length = 30)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonNicknamesId))
			return false;
		PersonNicknamesId castOther = (PersonNicknamesId) other;

		return ((this.getPersonPersonId() == castOther.getPersonPersonId())
				|| (this.getPersonPersonId() != null && castOther.getPersonPersonId() != null
						&& this.getPersonPersonId().equals(castOther.getPersonPersonId())))
				&& ((this.getNickname() == castOther.getNickname()) || (this.getNickname() != null
						&& castOther.getNickname() != null && this.getNickname().equals(castOther.getNickname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPersonPersonId() == null ? 0 : this.getPersonPersonId().hashCode());
		result = 37 * result + (getNickname() == null ? 0 : this.getNickname().hashCode());
		return result;
	}

}
