package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reviews1 generated by hbm2java
 */
@Entity
@Table(name = "reviews1", catalog = "dbtrain")
public class Reviews1 implements java.io.Serializable {

	private int reviewId;
	private Users1 users1;
	private Videos1 videos1;
	private String score;
	private String remark;

	public Reviews1() {
	}

	public Reviews1(int reviewId, Users1 users1, Videos1 videos1, String score, String remark) {
		this.reviewId = reviewId;
		this.users1 = users1;
		this.videos1 = videos1;
		this.score = score;
		this.remark = remark;
	}

	@Id

	@Column(name = "review_id", unique = true, nullable = false)
	public int getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(int reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public Users1 getUsers1() {
		return this.users1;
	}

	public void setUsers1(Users1 users1) {
		this.users1 = users1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "videoId", nullable = false)
	public Videos1 getVideos1() {
		return this.videos1;
	}

	public void setVideos1(Videos1 videos1) {
		this.videos1 = videos1;
	}

	@Column(name = "score", nullable = false, length = 45)
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	@Column(name = "remark", nullable = false, length = 45)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
