package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reviews generated by hbm2java
 */
@Entity
@Table(name = "reviews", catalog = "videodb")
public class Reviews implements java.io.Serializable {

	private Integer reviewId;
	private Users users;
	private Videos videos;
	private String score;
	private String remark;

	public Reviews() {
	}

	public Reviews(Users users, Videos videos, String score, String remark) {
		this.users = users;
		this.videos = videos;
		this.score = score;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "review_id", unique = true, nullable = false)
	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "videoId", nullable = false)
	public Videos getVideos() {
		return this.videos;
	}

	public void setVideos(Videos videos) {
		this.videos = videos;
	}

	@Column(name = "score", nullable = false, length = 45)
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	@Column(name = "remark", nullable = false, length = 45)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
