package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tagscollection generated by hbm2java
 */
@Entity
@Table(name = "tagscollection", catalog = "videodb")
public class Tagscollection implements java.io.Serializable {

	private Integer tagId;
	private String tag;
	private Set<Videos> videoses = new HashSet<Videos>(0);

	public Tagscollection() {
	}

	public Tagscollection(String tag, Set<Videos> videoses) {
		this.tag = tag;
		this.videoses = videoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tagId", unique = true, nullable = false)
	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	@Column(name = "tag", length = 45)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "video_tags", catalog = "videodb", joinColumns = {
			@JoinColumn(name = "tagsId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "videoId", nullable = false, updatable = false) })
	public Set<Videos> getVideoses() {
		return this.videoses;
	}

	public void setVideoses(Set<Videos> videoses) {
		this.videoses = videoses;
	}

}
