package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", catalog = "dbtrain")
public class Tags implements java.io.Serializable {

	private Integer tagid;
	private String tag;
	private Set<Videos1> videos1s = new HashSet<Videos1>(0);

	public Tags() {
	}

	public Tags(String tag, Set<Videos1> videos1s) {
		this.tag = tag;
		this.videos1s = videos1s;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tagid", unique = true, nullable = false)
	public Integer getTagid() {
		return this.tagid;
	}

	public void setTagid(Integer tagid) {
		this.tagid = tagid;
	}

	@Column(name = "tag", length = 30)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "video_tags1", catalog = "dbtrain", joinColumns = {
			@JoinColumn(name = "tagId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "videoId", nullable = false, updatable = false) })
	public Set<Videos1> getVideos1s() {
		return this.videos1s;
	}

	public void setVideos1s(Set<Videos1> videos1s) {
		this.videos1s = videos1s;
	}

}
