package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users1 generated by hbm2java
 */
@Entity
@Table(name = "users1", catalog = "dbtrain", uniqueConstraints = @UniqueConstraint(columnNames = "EMAIL"))
public class Users1 implements java.io.Serializable {

	private int id;
	private String email;
	private String password;
	private String firstname;
	private String lastname;
	private String gender;
	private Integer age;
	private String street;
	private String state;
	private String city;
	private Set<Reviews1> reviews1s = new HashSet<Reviews1>(0);
	private Set<Comedians1> comedians1s = new HashSet<Comedians1>(0);

	public Users1() {
	}

	public Users1(int id) {
		this.id = id;
	}

	public Users1(int id, String email, String password, String firstname, String lastname, String gender, Integer age,
			String street, String state, String city, Set<Reviews1> reviews1s, Set<Comedians1> comedians1s) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.gender = gender;
		this.age = age;
		this.street = street;
		this.state = state;
		this.city = city;
		this.reviews1s = reviews1s;
		this.comedians1s = comedians1s;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "EMAIL", unique = true, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "FIRSTNAME", length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", length = 30)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "GENDER", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "AGE")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "STREET", length = 400)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "STATE", length = 400)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users1")
	public Set<Reviews1> getReviews1s() {
		return this.reviews1s;
	}

	public void setReviews1s(Set<Reviews1> reviews1s) {
		this.reviews1s = reviews1s;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "favcomedians1", catalog = "dbtrain", joinColumns = {
			@JoinColumn(name = "userId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "comedianId", nullable = false, updatable = false) })
	public Set<Comedians1> getComedians1s() {
		return this.comedians1s;
	}

	public void setComedians1s(Set<Comedians1> comedians1s) {
		this.comedians1s = comedians1s;
	}

}
