package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Userv1 generated by hbm2java
 */
@Entity
@Table(name = "userv1", catalog = "dbtrain")
public class Userv1 implements java.io.Serializable {

	private Userv1Id id;

	public Userv1() {
	}

	public Userv1(Userv1Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "email", column = @Column(name = "email", length = 30)),
			@AttributeOverride(name = "password", column = @Column(name = "password", length = 45)),
			@AttributeOverride(name = "gender", column = @Column(name = "gender", length = 10)),
			@AttributeOverride(name = "personId", column = @Column(name = "person_id")),
			@AttributeOverride(name = "street", column = @Column(name = "street", length = 30)),
			@AttributeOverride(name = "city", column = @Column(name = "city", length = 30)),
			@AttributeOverride(name = "state", column = @Column(name = "state", length = 30)) })
	public Userv1Id getId() {
		return this.id;
	}

	public void setId(Userv1Id id) {
		this.id = id;
	}

}
