package com.videoproject.entity3;
// Generated Apr 20, 2020, 12:09:43 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "videodb", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Users implements java.io.Serializable {

	private Integer userId;
	private String email;
	private String password;
	private String firstName;
	private String lastName;
	private String gender;
	private int age;
	private Set<Reviews> reviewses = new HashSet<Reviews>(0);
	private Set<Videos> videoses = new HashSet<Videos>(0);
	private Set<Favcomedians> favcomedianses = new HashSet<Favcomedians>(0);

	public Users() {
	}

	public Users(String email, String password, String firstName, String lastName, String gender, int age) {
		this.email = email;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.age = age;
	}

	public Users(String email, String password, String firstName, String lastName, String gender, int age,
			Set<Reviews> reviewses, Set<Videos> videoses, Set<Favcomedians> favcomedianses) {
		this.email = email;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.age = age;
		this.reviewses = reviewses;
		this.videoses = videoses;
		this.favcomedianses = favcomedianses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "email", unique = true, nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstName", nullable = false, length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "gender", nullable = false, length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Reviews> getReviewses() {
		return this.reviewses;
	}

	public void setReviewses(Set<Reviews> reviewses) {
		this.reviewses = reviewses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Videos> getVideoses() {
		return this.videoses;
	}

	public void setVideoses(Set<Videos> videoses) {
		this.videoses = videoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Favcomedians> getFavcomedianses() {
		return this.favcomedianses;
	}

	public void setFavcomedianses(Set<Favcomedians> favcomedianses) {
		this.favcomedianses = favcomedianses;
	}

}
